const menuData = {
    breakfast: [
          {name:"مربى", desc:" ", price:"5"},

        {name:"عسل", desc:" ", price:"5"},
        {name:"جبنة بلدية", desc:" ", price:"10"},
        {name:"جبنة صفراء", desc:" ", price:"12"},
        {name:"افوكادو", desc:" ", price:"8"},
        {name:"حمص", desc:" ", price:"7"},
        {name:"شكشوكة", desc:" ", price:"15"},
        {name:"قلاية بندورة", desc:" ", price:"15"},
        {name:"بطاطا وبيض", desc:" ", price:"10"},
        {name:"نقانق بالبيض", desc:" ", price:"15"},
        {name:"لبنة", desc:" ", price:"8"},
        {name:"بسطرما حبش", desc:"", price:"12"},
        {name:"زيت وزعتر", desc:"", price:"5"},
        {name:"صحن مروش", desc:"", price:"15"},
    
    ],

    meals: [
      
        {name:"وجبة سافوريا", desc:" ", price:"50"},
        {name:"وجبة كوردن بلو", desc:" ", price:"45"},
        {name:"تشاومين بالكاجو", desc:" ", price:"45"},
        {name:"ستيك دجاج بالمشروم", desc:" ", price:"40"},
        {name:"ستيك دجاج بالليمون", desc:" ", price:"40"},
        {name:"وجبة مسحب", desc:" ", price:"45"},
        {name:"تشكن استراجنوف", desc:" ", price:"40"},
        {name:"سكالوبيني", desc:" ", price:"50"},
        {name:"دجاج بالكاري", desc:" ", price:"35"},
    ],
    sandoish: [
        {name:"فطيرة سافوريا", desc:" ", price:"45"},
        {name:"فطيرة ذهبية", desc:" ", price:"35"},
        {name:"فطيرة الرانش", desc:" ", price:"30"},
        {name:"تشكن الاكيف", desc:" ", price:"30"},
        {name:"تشكن كنق", desc:" ", price:"30"},
        {name:"تشكن راب", desc:" ", price:"25"},
        {name:"تشكن بيتزا", desc:" ", price:"20"},
        {name:"سنيتشل اسبانيول", desc:" ", price:"20"},
        {name:"فاهيتا", desc:" ", price:"20"},
        {name:"دجاج كاري", desc:" ", price:"17"},
        {name:"تشكن برجر", desc:" ", price:"25"},
        {name:"بيف برجر", desc:" ", price:"30"},
        {name:"سماش برجر", desc:" ", price:"35"},
        {name:"برجر باظظ", desc:" ", price:"40"},
        {name:" باجيت مسحب بالجبنة ", desc:" ", price:"20"},
        {name:"صاج مسحب بالجبنة", desc:" ", price:"30"},
        {name:"صاج تشكن بيتزا", desc:" ", price:"25"},
        {name:"دجاج بانيه", desc:" ", price:"17"},

    ],
    shawrma:[
  {name:"شاورما عادي", desc:" ", price:"15"},
        {name:"شاورما دبل عادي", desc:" ", price:"17"},
        {name:"شاورما دبل دبل", desc:" ", price:"25"},
        {name:"شاورما سوري", desc:" ", price:"35"},
        {name:"شاورما اساور", desc:" ", price:"45"},
        {name:"شاورما savoria", desc:" ", price:"45"},
        {name:"صحن شاورما صغير", desc:" ", price:"40"},
        {name:"شاورما صاروخ", desc:" ", price:"40"},
        {name:"شاورما نابلسية", desc:" ", price:"50"},
        {name:"صفيحة شاورما", desc:" ", price:"40"},
        {name:"كيلو شاورما", desc:" ", price:"130"},

    ],
    desserts: [
        {name:"تشيز كيك", desc:" ", price:"15"},
        {name:"براونيز", desc:" ", price:"15"},

        {name:"لقيمات", desc:" ", price:"30"},
        {name:"كريب", desc:" ", price:"30"},
        {name:"ميني بان كيك", desc:" ", price:"25"},
        {name:"وافل", desc:" ", price:"30"},
        {name:"كنافة نوتيلا", desc:" ", price:"25"},
        {name:"تراميسو", desc:" ", price:"15"},
        {name:"بان كيك", desc:" ", price:"30"},

    ]
    ,
    drinkes: [
        {name:"هوت شوكليت", desc:" ", price:"15"},
        {name:"نس كافيه", desc:" ", price:"7"},
        {name:"كابتشينو", desc:" ", price:"7"},
        {name:"لاتيه", desc:" ", price:"10"},
        {name:"شاي", desc:" ", price:"5"},
        {name:"قهوة صغير", desc:" ", price:"10"},
        {name:"قهوة كبير", desc:" ", price:"15"},
        {name:"اسبريسو صغير", desc:" ", price:"12"},
        {name:"اسبريسو كبير", desc:" ", price:"15"},
        {name:"ايس كوفي", desc:" ", price:"15"},
        {name:"ايس لاتيه", desc:" ", price:"15"},
        {name:"ليمةن ونعنع", desc:" ", price:"10"},
        {name:"عصير الموسم", desc:" ", price:"15"},
        {name:"موهيتتو", desc:" ", price:"20"},
        {name:"فخفخينا", desc:" ", price:"25"},
        {name:"افوكادو", desc:" ", price:"25"},
        {name:"ميلك شيك", desc:" ", price:"15"},
        {name:"ميلك شيك اسبشل", desc:" ", price:"20"},
        {name:"ايس موكا", desc:" ", price:"15"},
        {name:"xl", desc:" ", price:"5"},
        {name:"كوكا كولا", desc:" ", price:"5"},
        {name:"مياه صغيرة", desc:" ", price:"-"},
        {name:"مياه كبيرة", desc:" ", price:"-"},
        {name:"بلو", desc:" ", price:"5"},
    ]
    ,
    salads: [
        {name:"كولسو كبير", desc:" ", price:"15"},
        {name:"صوص بيكانتي", desc:" ", price:"5"},
        {name:"حمص", desc:" ", price:"6"},
        {name:"سلطة خضراء", desc:" ", price:"10"},
        {name:"صوص رانش", desc:" ", price:"5"},
        {name:"صوص سافوريا", desc:" ", price:"5"},
        {name:"صحن تومية", desc:" ", price:"5"},
        {name:"ذرة بالمايونيز صغير", desc:" ", price:"10"},
        {name:"ذرة بالمايونيز كبير", desc:" ", price:"15"},
        {name:"ملفوف بالمايونيز صغير", desc:" ", price:"10"},
        {name:"ملفوف بالمايونيز كبير", desc:" ", price:"15"},
        {name:"سلطة تركية صغيرة", desc:" ", price:"8"},
        {name:"سلطة كولسلو صغير", desc:" ", price:"10"},
    ]

    ,
    appetizers: [
        {name:"اصابع دجاج", desc:" ", price:"15"},
        {name:"اصابع جبنة", desc:" ", price:"20"},
        {name:"ورق عنب", desc:" ", price:"15"},
        {name:"كبة", desc:" ", price:"16"},
        {name:"زيتون بانيه", desc:" ", price:"15"},
        {name:"صحن شيبسي صغير", desc:" ", price:"10"},
        {name:"صحن شيبسي كبير", desc:" ", price:"15"},
        {name:"تشيو فرايز", desc:" ", price:"20"},
        {name:"اكسترا جبنة", desc:" ", price:"5"},

    ]
};
